<?php
/**
 * @var $this Wsu_AdminTheme_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>wsu-brand/bug-logotype.svg') no-repeat left top;padding-left:59px;min-height:59px;">
        <a href="https://github.com/washingtonstateuniversity/WSUMAGE-storeutilities" target="_blank" style="float:right;">
            <img src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>wsu-brand/Github-fork-icon.svg" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?=$this->helper('storeutilities')->__('Store Utilities is the general utility module that other modules can be grafted of.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('storeutilities')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('storeutilities')->__('#')); ?>" target="_blank"><?php echo $this->helper('storeutilities')->__('here'); ?></a>.</p>
    </div>

	<p style="margin-bottom:0;"><?php echo $this->helper('storeutilities')->__('The Store utility extension aims to provide more core-ish functions and flow that surpasses the defaults of Magento.  This extension it designed to the be base of other extensions so they can predictably depend on access to the tools this Store utility extension provides'); ?>.</p>
</div>


<div class="box">
        
    <h3>Extarnal JS/CSS:</h3>
    <p><em><strong>addExternalItem</strong></em> also do the same as addItem but has 3 new types:</p>
    <ul>
        <li>external_css</li>
        <li>external_js</li>
        <li>cdn_js</li>
    </ul>
    <br/>
<div class="entry-edit-head collapseable"><a class="open" id="storeutilities_conf_html-head" onclick="Fieldset.toggleCollapse('storeutilities_conf_html'); return false;" href="#">Examples</a></div><fieldset class="config collapseable" id="storeutilities_conf_html"><legend>Extarnal JS/CSS Examples</legend>        <code><pre>
&lt;layout version=&quot;0.1.0&quot;&gt;
    &lt;default&gt;
        &lt;reference name=&quot;head&quot;&gt;
            &lt;action method=&quot;addItem&quot;&gt;
                &lt;type&gt;<strong>external_css</strong>&lt;/type&gt;
                &lt;name&gt;http://developer.yahoo.com/yui/build/reset/reset.css&lt;/name&gt;
                &lt;params/&gt;
                &lt;/action&gt;
            &lt;action method=&quot;addItem&quot;&gt;
                &lt;type&gt;<strong>external_js</strong>&lt;/type&gt;
                &lt;name&gt;http://yui.yahooapis.com/2.8.2r1/build/yahoo-dom-event/yahoo-dom-event.js&lt;/name&gt;
                &lt;params/&gt;
                &lt;/action&gt;
            &lt;action method=&quot;<strong>addExternalItem</strong>&quot;&gt;
                &lt;type&gt;<strong>external_js</strong>&lt;/type&gt;
                &lt;name&gt;http://yui.yahooapis.com/2.8.2r1/build/imageloader/imageloader-min.js&lt;/name&gt;
                &lt;params/&gt;
                &lt;/action&gt;
            &lt;action method=&quot;<strong>addExternalItem</strong>&quot;&gt;
                &lt;type&gt;<strong>external_css</strong>&lt;/type&gt;
                &lt;name&gt;http://yui.yahooapis.com/2.8.2r1/build/fonts/fonts-min.css&lt;/name&gt;
                &lt;params/&gt;
                &lt;/action&gt;
            &lt;action method=&quot;addItem&quot;&gt;
                &lt;type&gt;<strong>cdn_js</strong>&lt;/type&gt;
                &lt;name&gt;//code.jquery.com/jquery-migrate-1.2.1.min.js&lt;/name&gt;
                &lt;params/&gt;
                &lt;if/&gt;
                &lt;cond/&gt;
                &lt;window_obj&gt;jQuery&lt;/window_obj&gt;
                &lt;local_path&gt;/js/jquery-migrate-1.2.1.min.js&lt;/local_path&gt;
                &lt;/action&gt;
        &lt;/reference&gt;
    &lt;/default&gt;
    &lt;catalog_product_view&gt;
        &lt;reference name=&quot;head&quot;&gt;
            &lt;action method=&quot;removeItem&quot;&gt;
                &lt;type&gt;<strong>external_css</strong>&lt;/type&gt;
                &lt;name&gt;http://developer.yahoo.com/yui/build/reset/reset.css&lt;/name&gt;
                &lt;params/&gt;
                &lt;/action&gt;
            &lt;action method=&quot;removeItem&quot;&gt;
                &lt;type&gt;<strong>external_js</strong>&lt;/type&gt;
                &lt;name&gt;http://yui.yahooapis.com/2.8.2r1/build/yahoo-dom-event/yahoo-dom-event.js&lt;/name&gt;
                &lt;params/&gt;
                &lt;/action&gt;
            &lt;action method=&quot;<strong>removeExternalItem</strong>&quot;&gt;
                &lt;type&gt;<strong>external_js</strong>&lt;/type&gt;
                &lt;name&gt;http://yui.yahooapis.com/2.8.2r1/build/imageloader/imageloader-min.js&lt;/name&gt;
                &lt;params/&gt;
                &lt;/action&gt;
            &lt;action method=&quot;<strong>removeExternalItem</strong>&quot;&gt;
                &lt;type&gt;<strong>external_css</strong>&lt;/type&gt;
                &lt;name&gt;http://yui.yahooapis.com/2.8.2r1/build/fonts/fonts-min.css&lt;/name&gt;
                &lt;params/&gt;
                &lt;/action&gt;
        &lt;/reference&gt;
    &lt;/catalog_product_view&gt;
&lt;/layout&gt;
    </pre></code></fieldset><script type="text/javascript">//<![CDATA[
    Fieldset.applyCollapse('storeutilities_conf_html');
    //]]></script>

    <h4>Notes:</h4>
    <p>With <strong><em>cdn_js</em></strong> You'll want to note that <strong>&lt;params/&gt;&lt;if/&gt;&lt;cond/&gt;</strong> nodes must be there and before <em><strong>window_obj</strong></em> or <em><strong>local_path</strong></em>.  <em><strong>window_obj</strong></em> is the dom object relative to the javascript window object.  IE: window.jQuery is the target so you would load <strong>&lt;window_obj&gt;jQuery&lt;/window_obj&gt;</strong>.

</div>
<div class="box">
        
    <h3>jQuery:</h3>
    <p>Loads jQuery if set.</p>
</div>
<div class="box">
        
    <h3>LessCSS:</h3>
    <p>Less for CSS is able to be used.  Ensure that you change your layout xml files to use .less instead of .css where it's needed. For more information please look to <a href="http://lesscss.org/" target="_blank">Less documentation</a> on how to write your files.  Since this uses the <a href="https://github.com/leafo/lessphp" target="_blank">Lessphp</a> there is no client side building that could slow the user experience down.  This also means that you have this installed but it was not necessary to install the server level less compiler.</p>
</div>